### ISSUE TITLE
Remove the requirements of <effort> tag and SRDF

### ISSUE THREAD

**Issue by fbxiang** [haosulab/MPlib#2]
Since <effort> tag is often not provided in simulations, it would be better to allow URDF without it.
I would also be better to include a default SRDF collision pair generator.

**Comment by Colin97** [comment]
See 0.0.7 which ignores <velocity> and <effort> tags in URDF and allows SRDF file to be optional.

**Comment by Colin97** [comment]
MPlib now supports generating SRDF files (ignore collision pairs only). When no SRDF file is provided, MPlib will sample lots of configurations and find link pairs that will always collide, and then generate a SRDF file to ignore those link pairs.
