### ISSUE TITLE
avoid extreme trajectories

### ISSUE THREAD

**Issue by Colin97** [haosulab/MPlib#21]
Current algorithms ensure collision-free paths. However, some of these trajectories can come uncomfortably close to potential collisions, which is not ideal for real-world deployment. 

Are there methods to prevent such extreme trajectories or introduce a 'buffer threshold' option to ensure the generated paths maintain a safe distance from potential collisions?

**Comment by Lexseal** [comment]
related to #12. Add some optimizations to the trajectory.
