### ISSUE TITLE
Sapien to Planning World

### ISSUE THREAD

**Issue by Lexseal** [haosulab/MPlib#38]
It would be nice to have a function take a sapien world object and populate the planning world accordingly.

**Comment by Lexseal** [comment]
fcl seems to have a bug that causes segfault when colliding anything with a plane geometry.
> Collide with ground
[1]    223712 segmentation fault (core dumped)

According to [this post](https://github.com/flexible-collision-library/fcl/issues/12), the issue should have been fixed back in 2016 but the 2020 version of fcl still segfaults.

**Comment by KolinGuo** [comment]
Will be completed by #73
