### ISSUE TITLE
Planner init bug

### ISSUE THREAD

**Issue by Chaoqi-LIU** [haosulab/MPlib#65]
Hi, in planner.py, Planner.__init__(...), if the srdf == '', then on line 74, it calles self.generate_collision_pair(), before assign self_user_link_names. However, inside self.generate_collision_pair(), on line 138, n_link = len(self.user_link_names). This leads to AttributeError: 'Planner" object has no attribute 'user_link_names'.

**Comment by KolinGuo** [comment]
Hi, thank you for catching the bug!
We just pushed a fix regarding the bug. 
Please install the latest wheel from https://github.com/haosulab/MPlib/releases/tag/nightly.
