### ISSUE TITLE
Citing your work

### ISSUE THREAD

**Issue by rafaelBauer** [haosulab/MPlib#93]
Hello!

I am writing my master thesis and have used your library. I would like to cite your work. Do you have a preference or a BibTex entry that I could use?

Kind regards,
Rafael

**Comment by KolinGuo** [comment]
Hi Rafael, thank you for using MPlib and wanting to cite it in your thesis!

Please recheck the GitHub repo and use the `Cite this repository` button to download a Bibtex file.
