### ISSUE TITLE
Questions about pose coord in plan_pose

### ISSUE THREAD

**Issue by piqiuni** [haosulab/MPlib#94]
Hello, when running the plan_pose() function, it says the **target pose** is relative to the world frame. But after moving to the target pose, the **global pose** from sapien is not the same as the **target pose**.

And it seems the **global pose** from sapien is really based on the world frame. Why are they not the same?

And how could I plan the path based on **global pose** from sapien?
It confused me, I hope you can help
Thanks!

> demo.move_to_pose(pose1, )   # pose1 is the **target pose** 
> global_pose = griper_base_joint.get_global_pose()   # global_pose from sapien env

By the way, can you provide the URDF files used in the tutorial?

**Comment by Lexseal** [comment]
The urdf used in the tutorial is [here](https://github.com/haosulab/MPlib/tree/main/data/panda). I think they might be in the pip package too but I am not super sure.

Now, you said the global pose from sapien doesn't match the target pose, have you verified
1. if the end effector has moved to the target pose? you can check by querying what mplib thinks where the end effector is by [this](https://motion-planning-lib.readthedocs.io/latest/reference/kinematics/pinocchio.html#mplib.kinematics.pinocchio.PinocchioModel.get_link_pose)
2. is the pose of `griper_base_joint` the same as the pose of the end effector? Usually the pose of the joint is not the same as the pose of the link

**Comment by piqiuni** [comment]
Thanks for the reply @Lexseal.
I checked the pip package and it doesn't contain the data files.

I find that the joint pose of the end-effector is not the same as the link pose, and they have a Y-axis 90 degree rotation.
Thanks for sloving my problem!
