### ISSUE TITLE
Supporting robot base being non-zero

### ISSUE THREAD

**Issue by nature21** [haosulab/MPlib#96]
Thank you for your effort in developing this amazing and handy package. However, when I tried to specify the robot base to be a custom one by calling ``Planner.robot.set_base_pose()``,  it did not seem to work. This feature is critical for multi-robot manipulation. Currently, I work this around by applying a transformation to all the other objects except for the planned robot, but it seems to be inefficient. Besides, I found it hard to debug without being able to visualize the components of the planning world, because I can't check whether my conversion is correct. Do you happen to know how to visualize the planning world conveniently? Thank you so much!

**Comment by Lexseal** [comment]
Hi nature21,

Thank you for using mplib and providing feedback : ) When you said
>it did not seem to work

What in particular did not work? Note that during planning, if you are using `Planner.plan_pose`, keep in mind [this param](https://motion-planning-lib.readthedocs.io/latest/reference/Planner.html#mplib.Planner.plan_pose:~:text=the%20joint%20limits-,wrt_world,-%E2%80%93%20if%20true%2C%20interpret)

You can use [this API](https://motion-planning-lib.readthedocs.io/latest/reference/core/ArticulatedModel.html#mplib.ArticulatedModel.get_base_pose) to get the `base_pose` of the robot. Also, you can try [this API](https://motion-planning-lib.readthedocs.io/latest/reference/core/ArticulatedModel.html#mplib.ArticulatedModel.get_base_pose) to get the joint positions of the robot. Is that what you meant by "visualizing the components of the planning world?"
